name: CI- Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node_version: [12.x, 14.x, 16.x, 17.x, 18.x]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Start MinIO Server -> Run Unit and Functional Tests ( install, lint, browserify, test)
        env:
          CI: true
          MINIO_CI_CD: true
          MINT_MODE: full
          SERVER_ENDPOINT: localhost:9000
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
          MINIO_KMS_SECRET_KEY: "my-minio-key:OSMM+vkKUTCvQs9YL/CVMIMt43HFhkUpqJxTmGl6rYw="
          ACCESS_KEY: minio
          SECRET_KEY: minio123
          ENABLE_HTTPS: 0
        run: |
          Invoke-WebRequest -Uri https://dl.minio.io/server/minio/release/windows-amd64/minio.exe -OutFile $HOME/minio.exe
          Start-Process -NoNewWindow -FilePath "$HOME/minio.exe" -ArgumentList "-C", "$env:temp/minio-config", "server", "$env:temp/data{1...4}"
          npm install
          npm run lint
          npm run browserify
          npm run test

